// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Nulah.VSIX.TaskTool.ToolWindows.TaskManager
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTaskManagerWindowPackageString = "4118e776-54b6-4fec-a4d4-b4c6c02b65f5";
        public static Guid guidTaskManagerWindowPackage = new Guid(guidTaskManagerWindowPackageString);

        public const string guidNulahVSIXCmdSetString = "c965f18d-d59d-4ef7-851a-f60074cc6566";
        public static Guid guidNulahVSIXCmdSet = new Guid(guidNulahVSIXCmdSetString);

        public const string guidNulahTaskManagerCmdSetString = "7a343cf6-174f-466e-a6f2-91cfb72a0e4d";
        public static Guid guidNulahTaskManagerCmdSet = new Guid(guidNulahTaskManagerCmdSetString);

        public const string guidImagesString = "be552b3f-f7e1-4a28-bc8f-e085f60b5474";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NulahMenuGroup = 0x1000;
        public const int TopLevelMenu = 0x1001;
        public const int TaskManagerSubMenu = 0x1101;
        public const int TaskManagerSubGroup = 0x1100;
        public const int TaskManagerCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}