// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Nulah.VSIX.TaskTool
{
    internal sealed partial class Vsix
    {
        public const string Id = "Nulah.VSIX.TaskTool.210bf379-e573-4d9f-b6cb-2358d4172f12";
        public const string Name = "Nulah.TaskTool";
        public const string Description = @"A simple task list extension.";
        public const string Language = "en-US";
        public const string Version = "0.3.1";
        public const string Author = "Scott Schultz";
        public const string Tags = "Task list, Todo List";
    }
}
